// The installer speaks like UwURDP's default, playful tone, in German or English.

const de = {
  welcomeTitle: 'Hallo! Ich bin Nyu',
  welcomeBody: 'Ich richte UwURDP in ein paar Sekunden auf deinem {computer} ein.',
  againTitle: 'Schön, dich wiederzusehen!',
  againBody:
    'UwURDP {installed} ist schon da. Ich bringe es auf {version}, deine Hosts und dein Tresor bleiben, wo sie sind.',
  install: 'Installieren',
  update: 'Aktualisieren',
  reinstall: 'Neu installieren',
  options: 'Optionen',
  fewerOptions: 'Weniger Optionen',
  folder: 'Speicherort',
  change: 'Ändern …',
  desktopShortcut: 'Verknüpfung auf dem Desktop',
  runningTitle: 'UwURDP ist gerade offen',
  runningBody:
    'Ich schließe es kurz, damit ich weitermachen kann. Offene Remote-Sitzungen werden dabei getrennt.',
  closeAndContinue: 'Schließen und weiter',
  back: 'Zurück',
  progressInstall: 'Nyu richtet alles ein …',
  progressUpdate: 'Nyu bringt UwURDP auf den neuesten Stand …',
  progressUninstall: 'Nyu räumt auf …',
  quotes: [
    'Poliert die Bildschirme …',
    'Rückt Pixel zurecht …',
    'Prüft Zertifikate …',
    'Wärmt die Tastatur vor …',
    'Übt Ohrenwackeln …',
    'Rollt Kabel auf …',
    'Zählt die Tabs …',
  ],
  doneTitle: 'Fertig! ✧',
  doneBody: 'UwURDP ist bereit für deine Remote-Desktops.',
  updateDoneTitle: 'Alles frisch! ✧',
  updateDoneBody: 'UwURDP {version} startet gleich wieder.',
  tipsTitle: 'Kleine Tipps',
  tips: [
    'Jede Verbindung bekommt ihren eigenen Tab, auch mehrere zum selben Rechner.',
    'Hosts schon in RDCMan oder als .rdp-Dateien? Der Import holt sie rüber.',
    'Stabil oder Beta? Den Update-Kanal wählst du in den Einstellungen.',
  ],
  start: 'UwURDP starten',
  close: 'Schließen',
  errorTitle: 'Hoppla, das hat nicht geklappt',
  retry: 'Nochmal versuchen',
  uninstallTitle: 'Schade, dass du gehst …',
  uninstallBody: 'Ich entferne UwURDP von diesem {computer}.',
  removeInstead: 'Deinstallieren …',
  computerWindows: 'PC',
  computerMac: 'Mac',
  computerLinux: 'Rechner',
  keepData: 'Hosts, Tresor und Einstellungen behalten',
  keepDataHint:
    'Praktisch, falls du wiederkommst. Sonst lösche ich auch den Tresor mit allen gespeicherten Zugangsdaten.',
  uninstall: 'Deinstallieren',
  keep: 'Doch behalten',
  goodbyeTitle: 'Tschüss! (｡•́︿•̀｡)',
  goodbyeBody: 'UwURDP ist entfernt. Komm gern wieder vorbei.',
  soundOn: 'Ton an',
  soundOff: 'Ton aus',
  minimize: 'Minimieren',
  devBuild: 'Entwicklungs-Build: UwURDP ist hier nicht mit drin.',
  sandbox: 'Testmodus: Es wird nur in einem Testordner installiert.',
  footer: 'Version {version} · Open Source',
};

const en: typeof de = {
  welcomeTitle: "Hi! I'm Nyu",
  welcomeBody: "I'll set up UwURDP on your {computer} in a few seconds.",
  againTitle: 'Nice to see you again!',
  againBody:
    "UwURDP {installed} is already here. I'll bring it to {version}, and your hosts and vault stay where they are.",
  install: 'Install',
  update: 'Update',
  reinstall: 'Reinstall',
  options: 'Options',
  fewerOptions: 'Fewer options',
  folder: 'Location',
  change: 'Change …',
  desktopShortcut: 'Shortcut on the desktop',
  runningTitle: 'UwURDP is open right now',
  runningBody:
    "I'll close it for a moment so I can carry on. Open remote sessions will be disconnected.",
  closeAndContinue: 'Close and continue',
  back: 'Back',
  progressInstall: 'Nyu is setting everything up …',
  progressUpdate: 'Nyu is bringing UwURDP up to date …',
  progressUninstall: 'Nyu is tidying up …',
  quotes: [
    'Polishing the screens …',
    'Nudging pixels into place …',
    'Checking certificates …',
    'Warming up the keyboard …',
    'Practicing ear wiggles …',
    'Coiling cables …',
    'Counting tabs …',
  ],
  doneTitle: 'All done! ✧',
  doneBody: 'UwURDP is ready for your remote desktops.',
  updateDoneTitle: 'All fresh! ✧',
  updateDoneBody: 'UwURDP {version} starts again in a moment.',
  tipsTitle: 'Little tips',
  tips: [
    'Every connection gets its own tab, several to the same machine too.',
    'Hosts already in RDCMan or in .rdp files? The import brings them over.',
    'Stable or Beta? Pick the update channel in the settings.',
  ],
  start: 'Start UwURDP',
  close: 'Close',
  errorTitle: "Oops, that didn't work",
  retry: 'Try again',
  uninstallTitle: 'Sad to see you go …',
  uninstallBody: "I'll remove UwURDP from this {computer}.",
  removeInstead: 'Uninstall …',
  computerWindows: 'PC',
  computerMac: 'Mac',
  computerLinux: 'computer',
  keepData: 'Keep hosts, vault and settings',
  keepDataHint:
    'Handy if you come back. Otherwise I also delete the vault with every saved credential.',
  uninstall: 'Uninstall',
  keep: 'Keep it',
  goodbyeTitle: 'Bye! (｡•́︿•̀｡)',
  goodbyeBody: 'UwURDP is removed. Come back any time.',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  minimize: 'Minimize',
  devBuild: "Development build: UwURDP isn't packed inside.",
  sandbox: 'Test mode: installs into a test folder only.',
  footer: 'Version {version} · Open source',
};

export type Texts = typeof de;

export const texts: Texts = navigator.language.toLowerCase().startsWith('de') ? de : en;

export function fill(template: string, values: Record<string, string>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => values[key] ?? '');
}
